kind: Service
apiVersion: v1
metadata:
  name: dashboard-service
  namespace: aiot
spec:
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  selector:
    app: dashboard
  type: ClusterIP

